---

# for debugger to display variables
- name: debug
  debug: 
    msg:
    - "Coordinator Raft Connection: {{ dingo_coordinator_raft_connection_list }}"
    - "Coordinator Exchange Connection: {{ dingo_coordinator_exchange_connection_list }}"
    - "Executor Raft Connection: {{ dingo_executor_raft_list }}"
    - "Executor Exchange Connection: {{ dingo_executor_exchange_list }}"

- name: "Generate dingo configuration files"
  template: src={{ item.src }} dest={{ item.dest }} owner={{ dingo_user }} group={{ dingo_group }} mode=0644
  with_items:
    - {
      src: "logback-coordinator.xml.j2",
      dest: "{{ dingo_home }}/conf/logback-coordinator.xml"
    }
    - {
      src: "logback-executor.xml.j2",
      dest: "{{ dingo_home }}/conf/logback-executor.xml"
    }
    - {
      src: "logback-sqlline.xml.j2",
      dest: "{{ dingo_home }}/conf/logback-sqlline.xml"
    }
    - {
      src: "config.yaml.j2",
      dest: "{{ dingo_home}}/conf/config.yaml"
    }

- name: "Remove unused configure files"
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ dingo_home }}/conf/logback.xml"
