---

# start coordinator
- name: "Start Coordinator using Script"
  shell: "/bin/bash ./bin/start-coordinator.sh > log/coordinator.out 2>&1" 
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_coordinator

# start executor
- name: "Start Executor using Shell Script"
  shell: "/bin/bash ./bin/start-executor.sh > log/executor.out 2>&1" 
  args:
    chdir: "{{ dingo_home }}"
  when: is_dingo_executor

# start jdbc driver proxy