---

#---------------------------------
# 1. Prepare System
#---------------------------------
- hosts:
    - all_nodes
  tasks:
    - include_role: name=system
      when: install_system

#---------------------------------
# 2. Install JDK
#---------------------------------
- hosts:
    - all_nodes
  tasks:
    - include_role: name=jdk
      when: install_java_sdk

#---------------------------------
# 3. Install Dingo nodes
#---------------------------------
- hosts:
    - all_nodes
  tasks:
    - include_role: name=dingo
      when: install_dingo